.TH TBAR 1 "May 21, 2010" "Linux" "tbar manual"

.SH NAME
tBar \- a small taskbar written in TCL/TK

.SH SYNOPSIS
.B tbar
.RB [ \--config
.IR FILE
.RB ]

.SH DESCRIPTION
.Pp
\fBtBar\fP is a small taskbar application designed for leightweight window
managers. It provides basic system monitoring facilities such as:
.TP
*  CPU widget: temperature, frequency, cache, load, frequency scaling information ,supports multiple devices
.TP
* Memory / Swap widget: in use / free
.TP
* Ethernet widget: supports multiple devices
.TP
* Calendar / Clock widget with ICalendar support
.TP
* Customizable audio player widget
.TP
* Notification widget, reacting on boolean expressions
.TP
* Simple widget API
	
.SH OPTIONS
.TP
\fB\-\-config\fR \fIFILE\fR
specifies a config file to use instead of the global / user configuration file

.SH FILES
.TP
.I /etc/tbar/config.tcl
global configuration file
.TP
.I ~/.tbar/config.tcl
user specific config file
.TP
.I ~/.tbar/widget
user specific widget directory, place widgets here in order to make them loadable by tBar
.TP
.I ~/.tbar/lib
user specific library directory, place libraries along with a pkgIndex.tcl file here in order to make them loadable by tBar
.TP
.I ~/.tbar/icaldata
sqlite database storing user specific calendar data
.TP
.I ~/.tbar/log
tBar logfile

.SH BUGS
Send bug reports to <siyb@geekosphere.org>

.SH SEE ALSO
The project's website can be found at http://siyb.mount.at/tbar/

.SH AUTHOR
tBar and its documentation was written by Patrick Sturm <siyb@geekosphere.org>
